#! /usr/bin/env bash

set -a
. .env
set +a

if [ -z $ADMIN_NAME ] || [ -z $ADMIN_EMAIL ] || [ -z $ADMIN_PASSWORD ]; then
    echo "FATAL: Admin credentials are not set"
    exit 1
fi;
cat schema.sql | sqlite3 db.sqlite3

HASH=`python3 -c "from werkzeug.security import generate_password_hash as g; print(g('$ADMIN_PASSWORD'))"`

sqlite3 db.sqlite3 "insert into users(name, email, password, is_admin) values('$ADMIN_NAME', '$ADMIN_EMAIL', '$HASH', true) 
        on conflict (email) do update set name = '$ADMIN_NAME', password = '$HASH'"
    
python3 -c "import server; server.start()"